cmake_minimum_required(VERSION 4.1)
project(clase28_26)

set(CMAKE_CXX_STANDARD 20)

add_executable(clase28_26 main.cpp
        Producto.cpp
        Producto.h
        NoPerecedero.cpp
        NoPerecedero.h
        Electronicos.cpp
        Electronicos.h
        Abarrotes.cpp
        Abarrotes.h
        Fecha.cpp
        Fecha.h
        Cliente.cpp
        Cliente.h
        ClienteFrecuente.cpp
        ClienteFrecuente.h
        Caja.cpp
        Caja.h
        Factura.cpp
        Factura.h
        Habitacion.cpp
        Habitacion.h
        Casa.cpp
        Casa.h)
